### ISSUE TITLE
[Question] what is the role of  generated GraalFeature class

### ISSUE THREAD

**Issue by lost4git** [dansiviter/juli#99]
### JULI Version

master

### What should happen?

As far as I know, reflection is not used in the generated code, why do we need to generate GraalFeature class and register some configs?

### What actually happen?

GraalFeature class generated

**Comment by dansiviter** [comment]
There is a small amount of reflection via `uk.dansiviter.juli.LogProducer` to get a handle on the generated logger in lazy load scenarios. It is likely this is no longer needed as Graal has moved on.

**Comment by lost4git** [comment]
@dansiviter I see, thanks
